image:
  repository: vespaengine/vespa
  tag: "8.738.17"
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: "2"
    memory: "3Gi"
  limits:
    cpu: "2"
    memory: "3Gi"


backup:
  aws:
    accessKeyId: "YOUR_KEY_ID"
    secretAccessKey: "YOUR_ACCESS_KEY"
  image:
    repository: vespa-backup
    tag: latest
    pullPolicy: Never
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "1"
      memory: "3Gi"

service:
  httpPort: 8080
  configPort: 19071
